version: "3.9"

services:
  wireguard:
    image: tyisi/wireguard
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules
      - /sys:/sys:rw
