version: "3.9"

services:
  wireguard:
    image: tyisi/wireguard
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules
      - /sys:/sys:rw
